FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive


WORKDIR /home/mpei_bot

COPY ./ ./

RUN apt update -y
RUN apt install -y git
RUN apt install -y postgresql gcc python3-dev musl-dev
RUN apt install -y python3-pip
RUN apt install -y wkhtmltopdf
RUN pip3 install -r /home/mpei_bot/requirements.txt

RUN chmod 7700 /tmp

CMD python3 main.py