FROM jobber

USER root

EXPOSE 6379

EXPOSE 5432

RUN apk add python3-dev

COPY ./.jobber /home/jobberuser
COPY ./delete_schedule.py /main
COPY ./saving_redis_dump.py /main

RUN apk add py-pip

RUN pip3 install yadisk==1.2.14

RUN chmod a-rwx /home/jobberuser/.jobber
RUN chmod a+r /home/jobberuser/.jobber
