FROM alpine

WORKDIR /home/mpei_bot

COPY ./ ./

RUN apk update
RUN apk add git
RUN apk add postgresql-dev gcc python3-dev musl-dev
RUN apk add py-pip
RUN apk add libxml2-dev=2.9.10-r5
RUN apk add libxslt-dev=1.1.34-r0
RUN apk add wkhtmltopdf
RUN pip3 install -r /home/mpei_bot/requirements.txt

CMD python3 main.py