FROM jobber

USER root

RUN apk add python3-dev

COPY ./.jobber /home/jobberuser
COPY ./delete_schedule.py /main/delete_schedule.py
COPY ./saving_redis_dump.py /main/delete_schedule.py
COPY ./temp.json /main/temp.json

RUN apk add py-pip

RUN pip3 install yadisk==1.2.14


RUN chmod a-rwx /home/jobberuser/.jobber
RUN chmod a+r /home/jobberuser/.jobber
USER jobberuser