FROM alpine

WORKDIR /home/mpei_bot

COPY ./ ./

RUN apk update
RUN apk add git
RUN apk add python3=3.8.5
RUN apk add py-pip
RUN pip3 install -r /home/mpei_bot/requirements.txt

CMD ["python3", "main.py"]