version: "3.0"
services:
  redis_dump:
    networks:
      - main
    image:
      dudude/redis_get_dump
    depends_on:
      - redis
    environment:
      OAUTH_TOKEN: "AgAAAAA50RCLAAadkzzPvN2mYkRkiYmUUQeEssY"
  db_postgres:
    networks:
      - main
    image: dudude/postgres
    container_name: postgres_main
    restart: "always"
    environment:
      POSTGRES_PASSWORD: "Mersedes55"
      POSTGRES_DB: "mpei_bot"
      PG_DATA: /var/lib/postgresql/data/pgdata
  redis:
    networks:
      - main
    image: dudude/redis
    restart: "always"
    ports:
    - 6379:6379
  app:
    user: root
    depends_on:
      - redis
      - redis_dump
      - redis_save_yandex_disk
      - db_postgres
    networks:
      - main
    image: dudude/mpei_bot_ubuntu
    environment:
      TOKEN: "1190382600:AAGITzZDFTn1HeQmUUUyciyIQkaCseYUGwI"
      XDG_RUNTIME_DIR: "/tmp"
      passwd: "Mersedes55"
    restart: "always"
  redis_save_yandex_disk:
    depends_on:
      - redis
    environment:
      OAUTH_TOKEN: "AgAAAAA50RCLAAadkzzPvN2mYkRkiYmUUQeEssY"
    networks:
      - main
    image: dudude/jobber
    restart: "no"

networks:
  main:
    driver: bridge
