version: '1'
services:
  redis_dump:
    image:
      dudude/get_redis_dump
    links:
      - db_redis
    environment:
      OAUTH_TOKEN: AgAAAAA50RCLAAadkzzPvN2mYkRkiYmUUQeEssY
  db_postgres:
    image: postgres:11.4-alpine
    container_name: postgres_main
    restart: always
    environment:
      POSTGRES_PASSWORD: Mersedes55
      POSTGRES_USER: mpei_bot_user
      POSTGRES_DB: mpei_bot
      PG_DATA: /var/lib/postgresql/data/pgdata
  db_redis:
    image: redis
    restart: always
  app:
    image: dudude/mpei_bot_ubuntu
    environment:
      TOKEN: 1190382600:AAGYuaGx6vgZgBSKXymZ0grwg8v2f8fb-iE
  redis_save_yandex_disk:
    image: dudude/jobber
    restart: no
